version: "3.7"
services:
    aste:
        image: mysql
        restart: always
        environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        env_file:
          - .env
        volumes:
        - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
        - ./img:/usr/src/app/img        
    node:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env
        depends_on:
          - aste