version: '3.7'
services:
    aste:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - TZ=Europe/Rome
          - PGTZ=Europe/Rome
        ports:
          - 5432:5432
        volumes: 
          - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql          
    web-node:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env  
        depends_on:
          - aste