version: "3.7"
services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        ports:
          - 3306:3306
        volumes:
        - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
                  
    node:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env
        depends_on:
          - db